// src/utils/views/Combobox.svelte
<script lang="ts" generics="T extends { label: string }">
  import assert from "assert-ts";
  import { Option } from "effect";
  import Divider from "src/utils/views/Divider.svelte";

  export let query: string;
  export let options: T[];
  export let onQueryChanged: (value: string) => void = () => {};
  export let onOptionSelected: (option: T) => void = () => {};
  export let onOptionFocused: (option: T) => void = () => {};

  let optionsImpl = [];

  let focusedIndex = Option.none<number>();

  function handleInput(event: any) {
    query = event.target.value;
    onQueryChanged(query);
  }

  function handleKeydown(event: any) {
    if (event.key === "ArrowDown") {
      event.preventDefault();

      const vv = Option.map(focusedIndex, (i) => {
        if (i === options.length - 1) {
          return i;
        }
        return i + 1;
      });
      const vv2 = Option.orElse(vv, () => Option.some(0));
      focusedIndex = vv2;
      assert(Option.isSome(focusedIndex));
      const option = options[focusedIndex.value];
      assert(option !== undefined);
      onOptionFocused(option);
    } else if (event.key === "ArrowUp") {
      event.preventDefault();

      const vv = Option.map(focusedIndex, (i) => {
        if (i === 0) {
          return 0;
        }
        return i - 1;
      });

      const vv2 = Option.orElse(vv, () => Option.some(options.length - 1));
      focusedIndex = vv2;
      assert(Option.isSome(focusedIndex));
      const option = options[focusedIndex.value];
      assert(option !== undefined);
      onOptionFocused(option);
    } else if (event.key === "Enter") {
      event.preventDefault();
      if (Option.isSome(focusedIndex)) {
        const option = options[focusedIndex.value];
        assert(option !== undefined);
        onOptionSelected(option);
      }
    }
  }

  let input;

  function isIndexFocused(idx: number) {
    const extracted = Option.filter(focusedIndex, (i) => i === idx);
    return Option.isSome(extracted);
  }
</script>

<div
  class="absolute top-full left-0 mt-2 p-2 bg-white ring rounded-sm flex flex-col gap-2"
>
  <div>
    <input
      class="outline-none"
      type="text"
      value={query}
      on:input={handleInput}
      bind:this={input}
      on:keydown={handleKeydown}
    />
  </div>
  <Divider />
  <div>
    {#each options as option, idx}
      <div class:bg-neutral-content={isIndexFocused(idx)}>
        <button on:click={() => onOptionSelected(option)}>{option.label}</button
        >
      </div>
    {/each}
  </div>
</div>

// src/features/Combobox.tsx
import { useState } from "react"
import { Divider } from "./Divider"
import { useFloating, offset, autoUpdate, FloatingFocusManager } from "@floating-ui/react"
import { flip } from "effect/Function"
import { shift } from "effect/MutableList"

interface ComboboxProps {
  options: { label: string }[]
  onQueryChanged: (query: string) => void
  onSubmit: (index: number) => void
}

export function Combobox({ options, onQueryChanged, onSubmit }: ComboboxProps) {
  const [isOpen, setIsOpen] = useState(false)

  const { refs, floatingStyles, context } = useFloating({
    open: isOpen,
    onOpenChange: setIsOpen,
    middleware: [offset(10)],
    whileElementsMounted: autoUpdate,
  })

  const [index, setIndex] = useState(0)

  function onInput(event: React.FormEvent<HTMLInputElement>) {
    onQueryChanged(event.currentTarget.value)
  }

  function onKeyDown(event: React.KeyboardEvent<HTMLInputElement>) {
    switch (event.key) {
      case "ArrowUp":
        setIndex((index - 1 + options.length) % options.length)
        break
      case "ArrowDown":
        setIndex((index + 1) % options.length)
        break
      case "Enter":
        if (options.length === 0) {
          return
        }
        onSubmit(index)
    }
  }

  const optionEls = options.map((option, i) => (
    <div key={i} className={`${index === i ? "bg-neutral-content" : ""}`} onClick={() => onSubmit(i)}>
      {option.label}
    </div>
  ))

  return (
    <div ref={refs.setReference}>
      {isOpen && (
        <FloatingFocusManager context={context} modal={false}>
          <div
            ref={refs.setFloating}
            className="p-2 bg-white ring rounded-sm flex flex-col gap-2"
            style={{ inset: "unset", ...floatingStyles }}
          >
            <div>
              <input className="outline-none" type="text" onInput={onInput} onKeyDown={onKeyDown} />
            </div>
            <Divider />
            <div>{optionEls}</div>
          </div>
        </FloatingFocusManager>
      )}
    </div>
  )
}
